#!/bin/bash

mkdir ~/.avr_sdk
cp -r ./tools/createNewAvrProject/dependencies ~/.avr_sdk/
sudo cp  ./tools/createNewAvrProject/createNewAvrProject /usr/local/bin
sudo cp  ./tools/rawSerialMonitor/rawSerialMonitor /usr/local/bin
sudo chmod +x /usr/local/bin/createNewAvrProject
sudo chmod +x /usr/local/bin/rawSerialMonitor