#!/bin/bash
echo "Installing dependencies..."
if [ -d ~/.avr_sdk ]; then rm -Rf ~/.avr_sdk; fi
mkdir ~/.avr_sdk
cp -r ./tools/createNewAvrProject/dependencies ~/.avr_sdk/
sudo cp  ./tools/createNewAvrProject/createNewAvrProject /usr/local/bin
sudo cp  ./tools/rawSerialMonitor/rawSerialMonitor /usr/local/bin
sudo cp  ./tools/AsmCyclesCounter/app/asmCycleCounter /usr/local/bin
sudo chmod +x /usr/local/bin/createNewAvrProject
sudo chmod +x /usr/local/bin/rawSerialMonitor
sudo chmod +x /usr/local/bin/asmCycleCounter
echo "Done."
