#!/bin/bash
echo "Removing files..."
if [ -d ~/.avr_sdk ]; then 
	$(rm -r ~/.avr_sdk)
fi

if [ -f /usr/local/bin/createNewAvrProject ]; then 
	$(sudo rm /usr/local/bin/createNewAvrProject)
fi

if [ -f /usr/local/bin/rawSerialMonitor ]; then 
	$(sudo rm /usr/local/bin/rawSerialMonitor)
fi

if [ -f /usr/local/bin/asmCycleCounter ]; then 
	$(sudo rm /usr/local/bin/asmCycleCounter)
fi
if [ -f /usr/local/bin/createCppClass ]; then 
	$(sudo rm /usr/local/bin/createCppClass)
fi
echo "Done."