#!/bin/bash
echo "Removing files..."
if [ -d ~/.avr_sdk ]; then 
	$(rm -r ~/.avr_sdk)
fi

if [ -d /usr/local/bin/createNewAvrProject ]; then 
	$(sudo rm /usr/local/bin/createNewAvrProject)
fi

if [ -d /usr/local/bin/rawSerialMonitor ]; then 
	$(sudo rm /usr/local/bin/rawSerialMonitor)
fi

if [ -d /usr/local/bin/asmCycleCounter ]; then 
	$(sudo rm /usr/local/bin/asmCycleCounter)
fi
echo "Done."