#include "atmega2560.h"




/*
constexpr u16t PROGMEM __flashMappedPort[]  = {
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PINE), //0 RX0 - RXD0/PCINT8
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PINE), //1 TX0 - TXD0
LETTERx(LETTER_B)  | TIMERx(TIMER_3)  | PWM_GROUP(PWM16BIT) | BIT(DD4) |  PINx(_PINE), //2 - 0C3B/INT4
LETTERx(LETTER_C)  | TIMERx(TIMER_3)  | PWM_GROUP(PWM16BIT) | BIT(DD5) |  PINx(_PINE), //3	- OC3C/INT5
LETTERx(LETTER_B)  | TIMERx(TIMER_0)  | PWM_GROUP(PWM8BIT)  | BIT(DD5) |  PINx(_PING), //4			| OC0B
LETTERx(LETTER_A)  | TIMERx(TIMER_3)  | PWM_GROUP(PWM16BIT) | BIT(DD3) |  PINx(_PINE), //5			| OC3A/AIN1
LETTERx(LETTER_A)  | TIMERx(TIMER_4)  | PWM_GROUP(PWM16BIT) | BIT(DD3) |  PINx(_PINH), //6			| OC4A
LETTERx(LETTER_B)  | TIMERx(TIMER_4)  | PWM_GROUP(PWM16BIT) | BIT(DD4) |  PINx(_PINH), //7			| OC4B
LETTERx(LETTER_C)  | TIMERx(TIMER_4)  | PWM_GROUP(PWM16BIT) | BIT(DD5) |  PINx(_PINH), //8			| OC4C
LETTERx(LETTER_B)  | TIMERx(TIMER_2)  | PWM_GROUP(PWM8BIT)  | BIT(DD6) |  PINx(_PINH), //9			| OC2B
LETTERx(LETTER_A)  | TIMERx(TIMER_2)  | PWM_GROUP(PWM8BIT)  | BIT(DD4) |  PINx(_PINB), //10		| OC2A/PCINT4
LETTERx(LETTER_A)  | TIMERx(TIMER_1)  | PWM_GROUP(PWM16BIT) | BIT(DD5) |  PINx(_PINB), //11		| OC1A/PCINT5
LETTERx(LETTER_B)  | TIMERx(TIMER_1)  | PWM_GROUP(PWM16BIT) | BIT(DD6) |  PINx(_PINB), //12		| OC1B/PCINT6
LETTERx(LETTER_C)  | TIMERx(TIMER_1)  | PWM_GROUP(PWM16BIT) | BIT(DD7) |  PINx(_PINB), //13		| OC0A/OC1C/PCINT7
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PINJ), //14	TX3	| TXD3/PCINT10
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PINJ), //15	RX3	| RXD3/PCINT9
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PINH), //16	TX2	| TXD2
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PINH), //17	RX2	| RXD2
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD3) |  PINx(_PIND), //18	TX1	| TXD1/INT3
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD2) |  PINx(_PIND), //19	RX1	| RXD1/INT2
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PIND), //20	SDA	| SDA/INT1
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PIND), //21	SCL	| SCL/INT0
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PINA), //22		| AD0
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PINA), //23		| AD1
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD2) |  PINx(_PINA), //24		| AD2
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD3) |  PINx(_PINA), //25		| AD3
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD4) |  PINx(_PINA), //26		| AD4
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD5) |  PINx(_PINA), //27		| AD5
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD6) |  PINx(_PINA), //28		| AD6
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD7) |  PINx(_PINA), //29		| AD7
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD7) |  PINx(_PINC), //30		| A15
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD6) |  PINx(_PINC), //31		| A14
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD5) |  PINx(_PINC), //32		| A13
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD4) |  PINx(_PINC), //33		| A12
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD3) |  PINx(_PINC), //34		| A11
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD2) |  PINx(_PINC), //35		| A10
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PINC), //36		| A9
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PINC), //37		| A8
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD7) |  PINx(_PIND), //38		| T0
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD2) |  PINx(_PING), //39		| ALE
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PING), //40		| RD
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PING), //41		| WR
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD7) |  PINx(_PINL), //42		|
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD6) |  PINx(_PINL), //43		|
LETTERx(LETTER_C)  | TIMERx(TIMER_5)  | PWM_GROUP(PWM16BIT) | BIT(DD5) |  PINx(_PINL), //44		| OC5C
LETTERx(LETTER_B)  | TIMERx(TIMER_5)  | PWM_GROUP(PWM16BIT) | BIT(DD4) |  PINx(_PINL), //45		| OC5B
LETTERx(LETTER_A)  | TIMERx(TIMER_5)  | PWM_GROUP(PWM16BIT) | BIT(DD3) |  PINx(_PINL), //46		| OC5A
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD2) |  PINx(_PINL), //47		| T5
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PINL), //48		| ICP5
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PINL), //49		| ICP4
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD3) |  PINx(_PINB), //50	MISO| MISO/PCINT3
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD2) |  PINx(_PINB), //51	MOSI| MOSI/PCINT2
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PINB), //52	SCK	| SCK/PCINT1
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PINB), //53	SS	| SS/PCINT0

LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PINF), //A00	54	| ADC0
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PINF), //A01	55	| ADC1
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD2) |  PINx(_PINF), //A02	56	| ADC2
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD3) |  PINx(_PINF), //A03	57	| ADC3
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD4) |  PINx(_PINF), //A04	58	| ADC4/TMK
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD5) |  PINx(_PINF), //A05	59	| ADC5/TMS
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD6) |  PINx(_PINF), //A06	60	| ADC6
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD7) |  PINx(_PINF), //A07	61	| ADC7
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD0) |  PINx(_PINK), //A08	62	| ADC8/PCINT16
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD1) |  PINx(_PINK), //A09	63	| ADC9/PCINT17
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD2) |  PINx(_PINK), //A10	64	| ADC10/PCINT18
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD3) |  PINx(_PINK), //A11	65	| ADC11/PCINT19
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD4) |  PINx(_PINK), //A12	66	| ADC12/PCINT20
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD5) |  PINx(_PINK), //A13	67	| ADC13/PCINT21
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD6) |  PINx(_PINK), //A14	68	| ADC14/PCINT22
LETTERx(NO_LETTER) | TIMERx(NO_TIMER) | PWM_GROUP(0)        | BIT(DD7) |  PINx(_PINK) //A15	69	| ADC15/PCINT23
};

*/


/*
constexpr pin_setting _mappedPort[] {
	{&PINE, _BV(DD0), nullptr, 0, NO_LETTER}, //0 RX0 - RXD0/PCINT8
	{&PINE, _BV(DD1), nullptr, 0, NO_LETTER}, //1 TX0 - TXD0
	{&PINE, _BV(DD4), &TCCR3A, PWM16BIT, LETTER_B}, //2 - 0C3B/INT4
	{&PINE, _BV(DD5), &TCCR3A, PWM16BIT, LETTER_C}, //3	- OC3C/INT5
	{&PING, _BV(DD5), nullptr, 0, NO_LETTER}, //4			| OC0B
	{&PINE, _BV(DD3), &TCCR3A, PWM16BIT, LETTER_A}, //5			| OC3A/AIN1
	{&PINH, _BV(DD3), &TCCR4A, PWM16BIT, LETTER_A}, //6			| OC4A
	{&PINH, _BV(DD4), &TCCR4A, PWM16BIT, LETTER_B}, //7			| OC4B
	{&PINH, _BV(DD5), &TCCR4A, PWM16BIT, LETTER_C}, //8			| OC4C
	{&PINH, _BV(DD6), &TCCR2A, PWM8BIT,  LETTER_B}, //9			| OC2B
	{&PINB, _BV(DD4), &TCCR2A, PWM8BIT,  LETTER_A}, //10		| OC2A/PCINT4
	{&PINB, _BV(DD5), &TCCR1A, PWM16BIT, LETTER_A}, //11		| OC1A/PCINT5
	{&PINB, _BV(DD6), &TCCR1A, PWM16BIT, LETTER_B}, //12		| OC1B/PCINT6
	{&PINB, _BV(DD7), &TCCR1A, PWM16BIT, LETTER_C}, //13		| OC0A/OC1C/PCINT7
	{&PINJ, _BV(DD1), nullptr, 0, NO_LETTER}, //14	TX3	| TXD3/PCINT10
	{&PINJ, _BV(DD0), nullptr, 0, NO_LETTER}, //15	RX3	| RXD3/PCINT9
	{&PINH, _BV(DD1), nullptr, 0, NO_LETTER}, //16	TX2	| TXD2
	{&PINH, _BV(DD0), nullptr, 0, NO_LETTER}, //17	RX2	| RXD2
	{&PIND, _BV(DD3), nullptr, 0, NO_LETTER}, //18	TX1	| TXD1/INT3
	{&PIND, _BV(DD2), nullptr, 0, NO_LETTER}, //19	RX1	| RXD1/INT2
	{&PIND, _BV(DD1), nullptr, 0, NO_LETTER}, //20	SDA	| SDA/INT1
	{&PIND, _BV(DD0), nullptr, 0, NO_LETTER}, //21	SCL	| SCL/INT0
	{&PINA, _BV(DD0), nullptr, 0, NO_LETTER}, //22		| AD0
	{&PINA, _BV(DD1), nullptr, 0, NO_LETTER}, //23		| AD1
	{&PINA, _BV(DD2), nullptr, 0, NO_LETTER}, //24		| AD2
	{&PINA, _BV(DD3), nullptr, 0, NO_LETTER}, //25		| AD3
	{&PINA, _BV(DD4), nullptr, 0, NO_LETTER}, //26		| AD4
	{&PINA, _BV(DD5), nullptr, 0, NO_LETTER}, //27		| AD5
	{&PINA, _BV(DD6), nullptr, 0, NO_LETTER}, //28		| AD6
	{&PINA, _BV(DD7), nullptr, 0, NO_LETTER}, //29		| AD7
	{&PINC, _BV(DD7), nullptr, 0, NO_LETTER}, //30		| A15
	{&PINC, _BV(DD6), nullptr, 0, NO_LETTER}, //31		| A14
	{&PINC, _BV(DD5), nullptr, 0, NO_LETTER}, //32		| A13
	{&PINC, _BV(DD4), nullptr, 0, NO_LETTER}, //33		| A12
	{&PINC, _BV(DD3), nullptr, 0, NO_LETTER}, //34		| A11
	{&PINC, _BV(DD2), nullptr, 0, NO_LETTER}, //35		| A10
	{&PINC, _BV(DD1), nullptr, 0, NO_LETTER}, //36		| A9
	{&PINC, _BV(DD0), nullptr, 0, NO_LETTER}, //37		| A8
	{&PIND, _BV(DD7), nullptr, 0, NO_LETTER}, //38		| T0
	{&PING, _BV(DD2), nullptr, 0, NO_LETTER}, //39		| ALE
	{&PING, _BV(DD1), nullptr, 0, NO_LETTER}, //40		| RD
	{&PING, _BV(DD0), nullptr, 0, NO_LETTER}, //41		| WR
	{&PINL, _BV(DD7), nullptr, 0, NO_LETTER}, //42		|
	{&PINL, _BV(DD6), nullptr, 0, NO_LETTER}, //43		|
	{&PINL, _BV(DD5), &TCCR5A, PWM16BIT, LETTER_C}, //44		| OC5C
	{&PINL, _BV(DD4), &TCCR5A, PWM16BIT, LETTER_B}, //45		| OC5B
	{&PINL, _BV(DD3), &TCCR5A, PWM16BIT, LETTER_A}, //46		| OC5A
	{&PINL, _BV(DD2), nullptr, 0, NO_LETTER}, //47		| T5
	{&PINL, _BV(DD1), nullptr, 0, NO_LETTER}, //48		| ICP5
	{&PINL, _BV(DD0), nullptr, 0, NO_LETTER}, //49		| ICP4
	{&PINB, _BV(DD3), nullptr, 0, NO_LETTER}, //50	MISO| MISO/PCINT3
	{&PINB, _BV(DD2), nullptr, 0, NO_LETTER}, //51	MOSI| MOSI/PCINT2
	{&PINB, _BV(DD1), nullptr, 0, NO_LETTER}, //52	SCK	| SCK/PCINT1
	{&PINB, _BV(DD0), nullptr, 0, NO_LETTER}, //53	SS	| SS/PCINT0

	{&PINF, _BV(DD0), nullptr, 0, NO_LETTER}, //A00	54	| ADC0
	{&PINF, _BV(DD1), nullptr, 0, NO_LETTER}, //A01	55	| ADC1
	{&PINF, _BV(DD2), nullptr, 0, NO_LETTER}, //A02	56	| ADC2
	{&PINF, _BV(DD3), nullptr, 0, NO_LETTER}, //A03	57	| ADC3
	{&PINF, _BV(DD4), nullptr, 0, NO_LETTER}, //A04	58	| ADC4/TMK
	{&PINF, _BV(DD5), nullptr, 0, NO_LETTER}, //A05	59	| ADC5/TMS
	{&PINF, _BV(DD6), nullptr, 0, NO_LETTER}, //A06	60	| ADC6
	{&PINF, _BV(DD7), nullptr, 0, NO_LETTER}, //A07	61	| ADC7
	{&PINK, _BV(DD0), nullptr, 0, NO_LETTER}, //A08	62	| ADC8/PCINT16
	{&PINK, _BV(DD1), nullptr, 0, NO_LETTER}, //A09	63	| ADC9/PCINT17
	{&PINK, _BV(DD2), nullptr, 0, NO_LETTER}, //A10	64	| ADC10/PCINT18
	{&PINK, _BV(DD3), nullptr, 0, NO_LETTER}, //A11	65	| ADC11/PCINT19
	{&PINK, _BV(DD4), nullptr, 0, NO_LETTER}, //A12	66	| ADC12/PCINT20
	{&PINK, _BV(DD5), nullptr, 0, NO_LETTER}, //A13	67	| ADC13/PCINT21
	{&PINK, _BV(DD6), nullptr, 0, NO_LETTER}, //A14	68	| ADC14/PCINT22
	{&PINK, _BV(DD7), nullptr, 0, NO_LETTER}	//A15	69	| ADC15/PCINT23
};
*/
